// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJh7KONw5d_DFjuJAiOl1NW08sT-CPdA',
    appId: '1:181271560281:web:3e2577e911cf856ec6f148',
    messagingSenderId: '181271560281',
    projectId: 'smart-libary-app',
    authDomain: 'smart-libary-app.firebaseapp.com',
    storageBucket: 'smart-libary-app.appspot.com',
    measurementId: 'G-5WS7QJZ2WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDyRZG-HQxsRq-bFDwFwZ3L3DIrGkMaM',
    appId: '1:181271560281:android:4aa39af00f46a628c6f148',
    messagingSenderId: '181271560281',
    projectId: 'smart-libary-app',
    storageBucket: 'smart-libary-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCykdHcZ075Kq-N30EuLIT8qoSvuOJyHl8',
    appId: '1:181271560281:ios:83bc4854b7180f39c6f148',
    messagingSenderId: '181271560281',
    projectId: 'smart-libary-app',
    storageBucket: 'smart-libary-app.appspot.com',
    iosBundleId: 'com.thesis.smartLibaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCykdHcZ075Kq-N30EuLIT8qoSvuOJyHl8',
    appId: '1:181271560281:ios:82a4a6c4d202eebbc6f148',
    messagingSenderId: '181271560281',
    projectId: 'smart-libary-app',
    storageBucket: 'smart-libary-app.appspot.com',
    iosBundleId: 'com.thesis.smartLibaryApp.RunnerTests',
  );
}
